### ISSUE TITLE
No module named 'ua_parser'

### ISSUE THREAD

**Issue by yanerchuang** [a358003542/my-fake-useragent#1]
Collecting my_fake_useragent
  Using cached https://files.pythonhosted.org/packages/96/e7/f9f89d2549978f95b34d6dc0ff7a58894fe6a21e95ac691695578affebe4/my_fake_useragent-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pycharm-packaging\my-fake-useragent\setup.py", line 6, in <module>
        import my_fake_useragent
      File "C:\Users\Administrator\AppData\Local\Temp\pycharm-packaging\my-fake-useragent\my_fake_useragent\__init__.py", line 7, in <module>
        from .filter import filter_family, filter_os_family, filter_phone, \
      File "C:\Users\Administrator\AppData\Local\Temp\pycharm-packaging\my-fake-useragent\my_fake_useragent\filter.py", line 4, in <module>
        from ua_parser import user_agent_parser
    ModuleNotFoundError: No module named 'ua_parser'

**Comment by a358003542** [comment]
you need install the ua_parser module :
```
pip install ua_parser
```

**Comment by a358003542** [comment]
@yanerchuang next commit I will remove it , and now this module is not need any of other third module.

**Comment by luayua** [comment]
thanks.
